version: "3.8"

services:
    web:
        image: surovikin-testovoe/php:latest
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        working_dir: /app
        volumes:
            - .:/app
        depends_on:
            - postgres
            - kafka
        networks:
            - default

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - web
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: "${RESTART}"
        ports:
            - 80:80
            - 443:443
        networks:
            - default

    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: "${DB_DATABASE}"
            POSTGRES_PASSWORD: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_PASSWORD}"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - default

    zookeeper:
        image: confluentinc/cp-zookeeper:6.2.0
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - default

    kafka:
        image: confluentinc/cp-kafka:6.2.0
        container_name: kafka
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - default

volumes:
    postgres_data:
